### ISSUE TITLE
Problem installing on Scala IDE

### ISSUE THREAD

**Issue by ekrich** [dragos/typesafe-config-eclipse#10] opened 2016-02-01 19:13 UTC
I get the following error after dragging the Eclipse Icon top the open IDE. After trying the URL directly I see that the Feature is already installed so I'm not sure if this is normal behavior or not.
  `Typesafe Config Hocon Feature    1.0.2.201602011708  com.typesafe.hocon.sdk.feature.group    null`

eclipse.buildId=4.3.0-vfinal-2015-12-01T15:55:22Z-Typesafe (with no outstanding updates pending)
java.version=1.8.0_72
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.epp.mpc.ui
Error
Mon Feb 01 10:54:22 PST 2016
Unexpected exception while verifying features: 

``` java.lang.NullPointerException
    at java.net.URI$Parser.parse(URI.java:3042)
    at java.net.URI.<init>(URI.java:588)
    at org.eclipse.epp.internal.mpc.core.util.URLUtil.toURI(URLUtil.java:24)
    at org.eclipse.epp.internal.mpc.ui.operations.AbstractProvisioningOperation.addRepositories(AbstractProvisioningOperation.java:73)
    at org.eclipse.epp.internal.mpc.ui.operations.ResolveFeatureNamesOperation.run(ResolveFeatureNamesOperation.java:46)
    at org.eclipse.epp.internal.mpc.ui.wizards.FeatureSelectionWizardPage$4.run(FeatureSelectionWizardPage.java:304)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

![typesafe-config-eclipse](https://cloud.githubusercontent.com/assets/933058/12727691/df5bd788-c8d2-11e5-8145-7e00a5dc0303.PNG)

**Comment by dragos** [comment] 2016-02-01 22:17
I confirmed this issue with Scala IDE 4.2. It installed successfully in version 4.0, so it looks like there's a problem with more recent versions of Scala IDE.

Can you try installing using the update site (make sure to enable "Contact all update sites during install...")? At least for me, that seems to progress nicely (still installing)

**Comment by dragos** [comment] 2016-02-01 22:23
Nope, it installs correctly but then it's completely broken (including Scala features, it's all gone).

**Comment by dragos** [comment] 2016-02-01 23:07
This plugin depends on XText version 2.8, but Luna comes with version 2.7. I will push a new release with the proper versioned dependency. This will refuse to install on Luna, but adding the XText update site for 2.8  would make it work. The update site is 

http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.8.4

**Comment by mkurz** [comment] 2016-02-01 23:31
Just fyi: ScalaIDE will be using Mars with the next release by default (hopefully). There is an open bug in assembla which targets this change for the next IDE release. (Posting from phone so can't reference the ticket)

**Comment by ekrich** [comment] 2016-02-01 23:56
I'm not sure if you saw it in the original post that I had already installed previously but didn't realize it. I did try the update site and it resolved fine. That is how I found out I already had it installed. I can uninstall and try reinstalling if that will help.

**Comment by dragos** [comment] 2016-02-02 09:42
@ekrich there are several issues at play:
- Scala IDE has an issue with the Market Place client that leads to the above exception while installing via drag and drop
- version 1.0.2 of this plugin required XText, but without any version constraint. In fact, it needs at least version 2.8, which comes with Mars. I published 1.0.3 with the correct versioned dependency. For this workaround, if you want to keep using Scala IDE (based on Luna), you need to
  - add the XText update site to Available Update site (use http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.8.4)
  - reinstall (it should pick up 1.0.3 as a newer version, even if you have it installed) via update site

Let me know if this works for you

**Comment by ekrich** [comment] 2016-02-02 23:01
I can confirm this works for Luna 4.3
- Uninstall version 1.0.2
- Install xtext 2.8.4 with above link (selected redistributable only)
- Install typesafe-config-eclipse with link provided in the readme.

Thanks!

**Comment by dragos** [comment] 2016-02-03 07:03
Glad it worked for you. For the record, it should work without uninstalling the previous version, and without installing xtext manually. It's enough to have the Xtext update site in the list of available update sites, and Eclipse should be able to resolve all dependencies when installing this plugin./

**Comment by mkurz** [comment] 2017-01-12 13:29
Works with ScalaIDE 4.5.0 (which is based on Eclipse Neon).
I think we can finally close this issue.

**Comment by dragos** [comment] 2017-01-12 17:06
thanks!

**Closed as completed by dragos** 2017-01-12 17:06 UTC
